id: P003293
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23905
  title: རྡོ་རྗེ་རྣལ་འབྱོར་མའི་སྐོར་འབྲི་གུང་ལུགས
  author: ''
  volumes:
    a92cc5c2d08e4a509bbc41fadc944dec:
      image_group_id: I3205
      title: ''
      volume_number: 1
      total_pages: 401
      base_file: v001.txt
