id: I812DE1B3
legacy_id: P003293
ocr_import_info:
  bdrc_scan_id: W23905
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T00:02:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:04:30.011497+00:00'
last_modified: 2022-09-02 13:04:54.182015
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23905
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23905
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྡོ་རྗེ་རྣལ་འབྱོར་མའི་སྐོར་འབྲི་གུང་ལུགས།
statistics:
  ocr_word_mean_confidence_index: 0.8626390250962019
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I3205:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3205
      total_pages: 401
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3205.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8626390250962019
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
